name: Java CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # Other OS builds removed. Central build is a unix build anyway. // [windows-latest, macOS-latest]
        # Jenkins core dependency causes issues during deleting the temporary workspace in the test 'IntegrationTest.testPipelinePushLogsWithConnectionIssues'
        # "CompositeIO Unable to delete 'D:\a\elasticsearch-logs-plugin\elasticsearch-logs-plugin\target\tmp\j h1981224811615637958'"
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Test with Maven
      run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn verify
